# -*- coding: utf-8 -*-
"""Descriptive-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6lptRwRWkvIEUS62e84_yK9nG9TKvIU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

member_names=["Aman","riya","karan","sneha","rahul"]
ages=[22,25,24,23,26]
workout_hours=[2,1.5,2.5,1,3]
calories_burned=[750,350,600,300,500]
print("Fitness Dataset Loaded Successfully")

for i in range(len(member_names)):
  print("Member Name:",member_names[i])
  print("Age:",ages[i])
  print("Workout Hours:",workout_hours[i])
  print("Calories Burned:",calories_burned[i])

avg_workout=sum(workout_hours)/len(workout_hours)
print("Average workout hrs:",avg_workout)
h_calories=max(calories_burned)
l_calories=min(calories_burned)
print("Highest calories burned:",h_calories)
print("Lowest calories burned:",l_calories)
std_dev=np.std(calories_burned)
print("Standard Deviation of calories burned:",std_dev)

index=calories_burned.index(h_calories)
print("Member who burned highest calories:",member_names[index])
index=calories_burned.index(l_calories)
print("Member who burned lowest calories:",member_names[index])

plt.bar(member_names,calories_burned)
plt.xlabel("Member Names")
plt.ylabel("Calories Burned")
plt.title("Fitness Analysis")
plt.show()

plt.plot(member_names,calories_burned)
plt.xlabel("Member Names")
plt.ylabel("Calories Burned")
plt.title("Fitness Analysis")
plt.show()

hist1=plt.hist(calories_burned)
plt.xlabel("Calories Burned")
plt.ylabel("Frequency")
plt.title("Fitness Analysis")
plt.show()

piechart=plt.pie(calories_burned,labels=member_names)
plt.title("Fitness Analysis")
plt.show()

scatter=plt.scatter(ages,calories_burned)
plt.xlabel("Age")
plt.ylabel("Calories Burned")
plt.title("Fitness Analysis")
plt.show()