# -*- coding: utf-8 -*-
"""e-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zA3SOlpI2sxCUyjQGQ2ixD3htrrdygfB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/content/Ecommerce_Sales_Data_2024_2025 (1).csv')

df.head()

df.tail()

print("Initial Dataset Info:")
print(df.info())
print(df.shape)

df.drop_duplicates(inplace=True)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

#visualization
plt.figure(figsize=(6,4))
df['Category'].value_counts().plot(kind='bar')
plt.title("Category Type Count")
plt.xlabel("category Type")
plt.ylabel("Count")
plt.show()

#profit visualization by region
plt.figure(figsize=(6,4))
df.groupby('Region')['Profit'].sum().plot(kind='bar')
plt.title("Profit by Region")
plt.xlabel("Region")
plt.ylabel("Profit")
plt.show()

#pie chart
plt.figure(figsize=(6,4))
df['Category'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Category Type Count")
plt.ylabel("")
plt.show()

#bar plot category
plt.figure(figsize=(6,4))
df.groupby('Category')['Profit'].sum().plot(kind='bar')
plt.title("Profit by Category")
plt.xlabel("Category")
plt.ylabel("Profit")
plt.show()

#Category vs sales pie
plt.figure(figsize=(6,4))
df.groupby('Category')['Sales'].sum().plot(kind='pie', autopct='%1.1f%%')
plt.title("Category vs Sales")
plt.ylabel("")
plt.show()