# -*- coding: utf-8 -*-
"""Fitness_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBIsUd8zbvXsgdfJ5NO4h16dRtYT-ZT1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#read csv file
df = pd.read_csv('/content/fitness_tracker.csv')
df.head()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
df_scaled.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
df_scaled.head()

#find max calories burned
df_scaled['Calories_Burned'].max()

df_scaled['Calories_Burned'].min()

#mean
df_scaled['Calories_Burned'].mean()

#most active person
max_calories_idx = df_scaled['Calories_Burned'].idxmax()
user_id_most_active = df.loc[max_calories_idx, 'User_ID']
print(f"The User ID with the most calories burned is: {user_id_most_active}")

#most lazy person
min_calories_idx = df_scaled['Calories_Burned'].idxmin()
user_id_most_lazy = df.loc[min_calories_idx, 'User_ID']
print(f"The User ID with the most calories burned is: {user_id_most_lazy}")

#standard devation
df_scaled['Calories_Burned'].std()

#variance
df_scaled['Calories_Burned'].var()

#line plot
df_scaled['Calories_Burned'].plot(kind='bar')
plt.xlabel('Index')
plt.ylabel('Calories Burned')
plt.title('Calories Burned Over Time')
plt.show()

plt.scatter(df_scaled['Calories_Burned'], df_scaled['Steps'])
plt.xlabel('Calories Burned')
plt.ylabel('Steps')
plt.title('Calories Burned vs Steps')
plt.show()

bins = [0, 60, 120, df['Active_Minutes'].max()]
labels = ['Low Activity', 'Medium Activity', 'High Activity']
df['Activity_Level'] = pd.cut(df['Active_Minutes'], bins=bins, labels=labels, right=True, include_lowest=True)

activity_counts = df['Activity_Level'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(activity_counts, labels=activity_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of User Activity Levels (Active Minutes)')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()