# -*- coding: utf-8 -*-
"""Perscriptive-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AaZakBSo_GKJ4XLtg91AO8bsLzw0ShJn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = {
    'patient name': ['Jhon', 'Rahul', 'Aman'],
    'age': [50, 45, 22],
    'condition': ['critical','moderate','stable'],
    'oxygenlevel': [80, 90, 92],
    'Available beds': ['101','102','103']
}

df_patients = pd.DataFrame(data)
display(df_patients.head())

def assign_ward(row):
    if row['oxygenlevel'] <90:
        return 'ICU'
    else:
        return 'General Ward'
df_patients['Ward_Assignment'] = df_patients.apply(assign_ward, axis=1)
display(df_patients)

df_patients.groupby('Ward_Assignment').size().plot(kind='bar')
plt.show()