# -*- coding: utf-8 -*-
"""Predictive_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTQWsC1Dp12l2IK4URPyo7Gv5IEOiQ2z
"""

import pandas as pd
import numpy as np
num_samples = 10
tank_capacity = np.full(num_samples, 2000)
daily_usage = np.random.randint(50, 500, num_samples)
water_data = pd.DataFrame({
    'Tank Capacity (liters)': tank_capacity,
    'Daily Usage (liters)': daily_usage
})

display(water_data.head())

#average water consuption in aweek
avg_consuption=water_data['Daily Usage (liters)'].mean()
print(avg_consuption)

#finding the daily usage how much increased
water_data['Daily Usage (liters)'] = water_data['Daily Usage (liters)'] - avg_consuption
print(water_data['Daily Usage (liters)'])

#total water usage
total_water_usage = water_data['Daily Usage (liters)'].sum()
print(total_water_usage)

num_samples = 10
tank_capacity = np.full(num_samples, 2000)
daily_usage = np.random.randint(50, 500, num_samples)
water_data = pd.DataFrame({
    'Tank Capacity (liters)': tank_capacity,
    'Daily Usage (liters)': daily_usage
})

avg_consuption = water_data['Daily Usage (liters)'].mean()
initial_capacity = water_data['Tank Capacity (liters)'].iloc[0]

if avg_consuption > 0:
    days_to_depletion = initial_capacity / avg_consuption
    print(f"Based on an average daily usage of {avg_consuption:.2f} liters, the tank will last approximately {days_to_depletion:.2f} days.")
else:
    print("Average daily usage is zero or negative")

import matplotlib.pyplot as plt
plt.hist(water_data['Daily Usage (liters)'], bins=10, color='brown', edgecolor='black')
plt.xlabel('Daily Usage')
plt.ylabel('Frequency')
plt.title(' Daily Water Usage')
plt.show()

labels = ['Tank Capacity', 'Daily Usage']
sizes = [initial_capacity, avg_consuption]
colors = ['green', 'orange']
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
plt.axis('equal')

