# -*- coding: utf-8 -*-
"""predictive-weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148iWVfQvKMPzIZ-H0AHNFOsY_Nc2rj7I
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics

df=pd.read_csv('/content/Weather_Data.csv')

df.head()

df.tail()

print("Initial Dataset Info:")
print(df.info())
print(df.shape)

#average temperature
average_temperature = df['Temperature (°C)'].mean()
print(f"Average Temperature: {average_temperature:.2f}°C")

#average humidity
average_humidity = df['Humidity (%)'].mean()
print(f"Average Humidity: {average_humidity:.2f}%")

df.drop_duplicates(inplace=True)

#visualization bar plot
plt.bar(df['Weather Condition'].unique(), df['Weather Condition'].value_counts())
plt.xlabel('Weather Condition')
plt.ylabel('Frequency')
plt.title('Weather Distribution')
plt.show()

#piechart
plt.pie(df['Weather Condition'].value_counts(), labels=df['Weather Condition'].unique(), autopct='%1.1f%%')
plt.title('Weather Distribution')
plt.axis('equal')

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define X (features) and y (target)
X = df[['Temperature (°C)', 'Humidity (%)']]
y = df['Weather Condition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train a RandomForestClassifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

last_temperature = df.iloc[-1]['Temperature (°C)']
last_humidity = df.iloc[-1]['Humidity (%)']


tomorrow_data = pd.DataFrame([{'Temperature (°C)': last_temperature, 'Humidity (%)': last_humidity}])


tomorrow_weather_prediction = model.predict(tomorrow_data)

print(f"Predicted weather: {tomorrow_weather_prediction[0]}")

