# -*- coding: utf-8 -*-
"""Statistical analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgMHoMgW25Igh_v6yyTLNtJZOXKWGCcQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

marks=[70,80,90,60,100]
hours=[2,3,5,1,6]

print("Mean",np.mean(marks))
print("Median",np.median(marks))
print("variance",np.var(marks))
print("Standard deviation",np.std(marks))
print("correlation",np.corrcoef(marks))

plt.plot(marks)
plt.xlabel("Index")
plt.ylabel("Marks")
plt.title("Marks Over Index")
plt.show()

plt.plot(hours)
plt.xlabel("Index")
plt.ylabel("Hrs")
plt.title("hrs Over Index")
plt.show()

df=pd.DataFrame({'marks':marks,'hours':hours})
df.head()
df.tail()

